version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: buildweaver
      POSTGRES_PASSWORD: buildweaver
      POSTGRES_DB: buildweaver
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@buildweaver.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    environment:
      DATABASE_URL: postgres://buildweaver:buildweaver@postgres:5432/buildweaver
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
