import type { ProjectIR, Page } from '@buildweaver/libs';
import type { GeneratedFile } from '../../core/bundle';

const LOG_PREFIX = '[Codegen:Scaffold]';

const toComponentName = (name: string): string =>
  name
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join('') || 'Page';

const createPackageJson = (project: ProjectIR): string => {
  console.info(`${LOG_PREFIX} Generating package.json for "${project.metadata.name}"`);
  return JSON.stringify(
    {
      name: project.metadata.slug ?? 'buildweaver-react-app',
      private: true,
      version: '0.1.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview'
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        'react-router-dom': '^6.21.1'
      },
      devDependencies: {
        '@types/react': '^18.2.43',
        '@types/react-dom': '^18.2.17',
        '@vitejs/plugin-react': '^4.2.1',
        typescript: '^5.3.3',
        vite: '^5.0.8'
      }
    },
    null,
    2
  );
};

const createViteConfig = (): string => `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    open: true
  }
});
`;

const createTsconfig = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2020',
        useDefineForClassFields: true,
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'react-jsx',
        strict: true,
        noUnusedLocals: false,
        noUnusedParameters: false,
        noFallthroughCasesInSwitch: true
      },
      include: ['src']
    },
    null,
    2
  );

const createTsconfigNode = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        composite: true,
        skipLibCheck: true,
        module: 'ESNext',
        moduleResolution: 'bundler',
        allowSyntheticDefaultImports: true
      },
      include: ['vite.config.ts']
    },
    null,
    2
  );

const createIndexHtml = (projectName: string): string => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

const createEnvExample = (): string => `# Base URL for the backend API
VITE_API_BASE_URL=http://localhost:3000
`;

const createMainFile = (): string => `import React from 'react';
import ReactDOM from 'react-dom/client';
import { RouterProvider, createBrowserRouter } from 'react-router-dom';
import { routes } from './routes';
import './styles/global.css';

const router = createBrowserRouter(routes);

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
`;

const createUsePageDataHook = (): string => `import { useEffect, useState } from 'react';

const BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3000';

interface UsePageDataResult<T> {
  data: T | null;
  loading: boolean;
  error: string | null;
}

export function usePageData<T = Record<string, unknown>>(
  pageSlug: string
): UsePageDataResult<T> {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);

    fetch(\`\${BASE_URL}/api/page-data/\${pageSlug}\`)
      .then((res) => {
        if (!res.ok) throw new Error(\`Failed to load page data: \${res.status}\`);
        return res.json();
      })
      .then((result: T) => {
        if (!cancelled) {
          setData(result);
          setLoading(false);
        }
      })
      .catch((err: Error) => {
        if (!cancelled) {
          setError(err.message);
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [pageSlug]);

  return { data, loading, error };
}
`;

const createGlobalCss = (): string => `/* Generated by BuildWeaver */
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
    'Helvetica Neue', Arial, sans-serif;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  min-height: 100vh;
}

img,
picture,
video,
canvas,
svg {
  display: block;
  max-width: 100%;
}

input,
button,
textarea,
select {
  font: inherit;
}

/* Responsive column stacking */
@media (max-width: 768px) {
  .bw-stack-md {
    grid-template-columns: 1fr !important;
  }
}

@media (max-width: 1024px) {
  .bw-stack-lg {
    grid-template-columns: 1fr !important;
  }
}
`;

export const createRoutesFile = (
  pages: Array<{ componentName: string; page: Page }>
): string => {
  console.info(`${LOG_PREFIX} Generating routes for ${pages.length} page(s)`);

  if (pages.length === 0) {
    return `import type { RouteObject } from 'react-router-dom';

export const routes: RouteObject[] = [
  {
    path: '/',
    element: <div style={{ padding: '2rem', textAlign: 'center' }}>No pages configured yet.</div>
  }
];
`;
  }

  const imports = pages
    .map(
      ({ componentName }) =>
        `import { ${componentName} } from './pages/${componentName}';`
    )
    .join('\n');

  const routeEntries = pages
    .map(
      ({ componentName, page }) =>
        `  {\n    path: '${page.route}',\n    element: <${componentName} />\n  }`
    )
    .join(',\n');

  return `import type { RouteObject } from 'react-router-dom';
${imports}

export const routes: RouteObject[] = [
${routeEntries}
];
`;
};

const createReadme = (project: ProjectIR, pageCount: number): string => `# ${project.metadata.name}

Generated by [BuildWeaver](https://buildweaver.dev) code generator.

## Getting started

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`

## Pages

${pageCount} page(s) generated from the BuildWeaver IR.

## Environment variables

| Variable | Description | Default |
|----------|-------------|---------|
| \`VITE_API_BASE_URL\` | Backend API base URL | \`http://localhost:3000\` |
`;

export const createScaffoldFiles = (project: ProjectIR): GeneratedFile[] => {
  const pageCount = project.pages.length;
  console.info(`${LOG_PREFIX} Creating scaffold files for project "${project.metadata.name}" with ${pageCount} page(s)`);

  return [
    { path: 'package.json', contents: createPackageJson(project) },
    { path: 'vite.config.ts', contents: createViteConfig() },
    { path: 'tsconfig.json', contents: createTsconfig() },
    { path: 'tsconfig.node.json', contents: createTsconfigNode() },
    { path: 'index.html', contents: createIndexHtml(project.metadata.name) },
    { path: '.env.example', contents: createEnvExample() },
    { path: 'src/main.tsx', contents: createMainFile() },
    { path: 'src/hooks/usePageData.ts', contents: createUsePageDataHook() },
    { path: 'src/styles/global.css', contents: createGlobalCss() },
    { path: 'README.md', contents: createReadme(project, pageCount) }
  ];
};

export { toComponentName };
