import type { ProjectIR } from '@buildweaver/libs';
import type { GeneratedFile } from '../../core/bundle';

const LOG_PREFIX = '[Codegen:Express:Scaffold]';

export const createExpressPackageJson = (project: ProjectIR): string => {
  const hasDatabases = (project.databases?.length ?? 0) > 0;
  console.info(`${LOG_PREFIX} Generating package.json (hasDatabases=${hasDatabases})`);

  const deps: Record<string, string> = {
    express: '^4.18.2',
    cors: '^2.8.5',
    dotenv: '^16.3.1',
  };

  const devDeps: Record<string, string> = {
    typescript: '^5.3.3',
    '@types/express': '^4.17.21',
    '@types/cors': '^2.8.17',
    tsx: '^4.1.0',
  };

  if (hasDatabases) {
    deps['pg'] = '^8.11.3';
    devDeps['@types/pg'] = '^8.10.9';
  }

  return JSON.stringify(
    {
      name: `${project.metadata.slug ?? 'buildweaver'}-api`,
      private: true,
      version: '0.1.0',
      scripts: {
        dev: 'tsx watch src/index.ts',
        start: 'node dist/index.js',
        build: 'tsc -p tsconfig.json',
      },
      dependencies: deps,
      devDependencies: devDeps,
    },
    null,
    2,
  );
};

export const createExpressTsconfig = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2020',
        module: 'CommonJS',
        moduleResolution: 'Node',
        strict: true,
        esModuleInterop: true,
        outDir: 'dist',
        resolveJsonModule: true,
        declaration: true,
        sourceMap: true,
      },
      include: ['src'],
    },
    null,
    2,
  );

export const createGitignore = (): string =>
  ['node_modules/', 'dist/', '.env', '*.log', ''].join('\n');

export const createExpressReadme = (project: ProjectIR): string => {
  const pageCount = project.pages.length;
  const dbCount = project.databases?.length ?? 0;

  return `# ${project.metadata.name} - Express API

Generated by [BuildWeaver](https://buildweaver.dev) code generator.

## Getting started

\`\`\`bash
npm install
cp .env.example .env   # then fill in your database credentials
npm run dev
\`\`\`

## API Endpoints

${pageCount} page endpoint(s) generated.
${dbCount > 0 ? `${dbCount} database connection(s) configured.` : 'No databases configured yet.'}

## Environment variables

See \`.env.example\` for all available configuration.
`;
};

export const createScaffoldFiles = (project: ProjectIR): GeneratedFile[] => {
  console.info(
    `${LOG_PREFIX} Creating scaffold files for "${project.metadata.name}"`,
  );
  return [
    { path: 'package.json', contents: createExpressPackageJson(project) },
    { path: 'tsconfig.json', contents: createExpressTsconfig() },
    { path: '.gitignore', contents: createGitignore() },
    { path: 'README.md', contents: createExpressReadme(project) },
  ];
};
