import type { Page, PageDynamicInputRef, ProjectIR } from '@buildweaver/libs';
import type { CodegenAdapter } from '../core/adapter';
import { createBundle, type GeneratedFile } from '../core/bundle';
import { normalizeProject } from '../core/normalize';

const LOG_PREFIX = '[Codegen:FlutterAdapter]';

type FlutterPageModel = {
  id: string;
  name: string;
  route: string;
  slug: string;
  className: string;
  fileName: string;
  builderStateBase64: string;
  dynamicInputs: PageDynamicInputRef[];
};

const escapeDartString = (value: string): string =>
  value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, '\\n');

const toPackageName = (value: string): string => {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/(^_|_$)+/g, '');

  const withoutLeadingDigits = normalized.replace(/^[^a-z]+/, '');
  return withoutLeadingDigits || 'buildweaver_flutter_app';
};

const normalizeRoute = (route: string): string => {
  const trimmed = route.trim();
  if (!trimmed) {
    return '/';
  }
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
};

const routeToSlug = (route: string): string =>
  route
    .replace(/^\/+/, '')
    .replace(/\/+$/, '') || 'index';

const toClassName = (value: string): string =>
  value
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('') || 'GeneratedPage';

const toFileSegment = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/(^_|_$)+/g, '') || 'generated_page';

const encodeBase64 = (value: string): string => {
  const bytes = new TextEncoder().encode(value);
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  let result = '';

  for (let index = 0; index < bytes.length; index += 3) {
    const first = bytes[index];
    const hasSecond = index + 1 < bytes.length;
    const hasThird = index + 2 < bytes.length;
    const second = hasSecond ? bytes[index + 1] : 0;
    const third = hasThird ? bytes[index + 2] : 0;

    const combined = (first << 16) | (second << 8) | third;
    const charOne = alphabet[(combined >> 18) & 0x3f];
    const charTwo = alphabet[(combined >> 12) & 0x3f];
    const charThree = hasSecond ? alphabet[(combined >> 6) & 0x3f] : '=';
    const charFour = hasThird ? alphabet[combined & 0x3f] : '=';

    result += `${charOne}${charTwo}${charThree}${charFour}`;
  }

  return result;
};

const asObject = (value: unknown): Record<string, unknown> | null => {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return null;
  }
  return value as Record<string, unknown>;
};

const createFallbackBuilderState = (pageName: string): Record<string, unknown> => ({
  root: {
    id: 'root',
    props: {},
    children: []
  },
  content: [
    {
      type: 'Section',
      props: {
        id: `section-${toFileSegment(pageName)}`,
        heading: pageName,
        subheading: 'Generated by BuildWeaver',
        padding: '24px',
        backgroundColor: '#FFFFFF',
        contentSlot: [
          {
            type: 'Paragraph',
            props: {
              id: `paragraph-${toFileSegment(pageName)}`,
              content:
                'This page was generated from your BuildWeaver project. Update the page builder content to customize it.'
            }
          }
        ]
      }
    }
  ]
});

const coerceBuilderState = (
  value: unknown,
  pageName: string
): Record<string, unknown> => {
  const fallback = createFallbackBuilderState(pageName);
  const candidate = asObject(value);
  if (!candidate) {
    return fallback;
  }

  const root = asObject(candidate.root) ?? fallback.root;
  const content = Array.isArray(candidate.content)
    ? candidate.content
    : (fallback.content as unknown[]);

  const zones = asObject(candidate.zones);

  return {
    root,
    content,
    ...(zones ? { zones } : {})
  };
};

const ensurePages = (project: ProjectIR): Page[] => {
  if (project.pages.length > 0) {
    return project.pages;
  }

  return [
    {
      id: 'page-index',
      name: 'Home',
      route: '/',
      entry: {
        id: 'entry-index',
        key: 'entry-index',
        component: 'Section',
        label: 'Home',
        props: {},
        bindings: {},
        events: [],
        children: []
      },
      builderState: createFallbackBuilderState('Home'),
      dynamicInputs: []
    }
  ];
};

const reserveUnique = (base: string, seen: Map<string, number>): string => {
  const normalized = base || 'GeneratedValue';
  const count = seen.get(normalized) ?? 0;
  seen.set(normalized, count + 1);
  return count === 0 ? normalized : `${normalized}${count + 1}`;
};

const buildPageModels = (project: ProjectIR): FlutterPageModel[] => {
  const pages = ensurePages(project);
  const seenClassNames = new Map<string, number>();
  const seenFileNames = new Map<string, number>();

  return pages.map((page, index) => {
    const route = normalizeRoute(page.route);
    const slug = routeToSlug(route);

    const baseClassName = `${toClassName(page.name || slug || `Page${index + 1}`)}Page`;
    const className = reserveUnique(baseClassName, seenClassNames);

    const baseFileName = `${toFileSegment(slug || page.name || `page_${index + 1}`)}_page.dart`;
    const fileName = reserveUnique(baseFileName, seenFileNames);

    const builderState = coerceBuilderState(page.builderState, page.name || `Page ${index + 1}`);
    const builderStateBase64 = encodeBase64(JSON.stringify(builderState));

    return {
      id: page.id,
      name: page.name,
      route,
      slug,
      className,
      fileName,
      builderStateBase64,
      dynamicInputs: page.dynamicInputs ?? []
    };
  });
};

const createPubspec = (project: ProjectIR): string => {
  const packageName = toPackageName(project.metadata.slug ?? project.metadata.name);

  return `name: ${packageName}
description: Generated by BuildWeaver from IR ${project.version}
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
`;
};

const createAnalysisOptions = (): string => `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: false
`;

const createGitIgnore = (): string => `.dart_tool/
.packages
.flutter-plugins
.flutter-plugins-dependencies
.metadata
build/
coverage/
ios/Flutter/Flutter.framework
ios/Flutter/Flutter.podspec
`;

const createEnvFile = (): string => `# Base API URL used by generated API clients.
# This should point to the generated Express backend deployment.
API_BASE_URL=http://localhost:3000
`;

const createReadme = (project: ProjectIR, pages: FlutterPageModel[]): string => `# ${project.metadata.name} (Flutter + Express)

Generated by BuildWeaver.

## Contents

- Flutter frontend with Go Router
- Environment-based API client (uses API_BASE_URL)
- Runtime renderer for BuildWeaver page builder components
- Express backend scaffold (generated in the sibling backend folder)

## Flutter setup

1. Install Flutter SDK.
2. Run dependencies:

   flutter pub get

3. Configure API URL:

   cp .env.example .env
   # edit API_BASE_URL

4. Start app:

   flutter run

## Generated pages

${pages.map((page) => `- ${page.name} -> ${page.route}`).join('\n')}
`;

const createMainFile = (pages: FlutterPageModel[]): string => {
  const imports = pages
    .map((page) => `import 'pages/${page.fileName}';`)
    .join('\n');

  const routes = pages
    .map(
      (page) => `    GoRoute(
      path: '${escapeDartString(page.route)}',
      name: '${escapeDartString(page.id)}',
      builder: (context, state) => const ${page.className}(),
    )`
    )
    .join(',\n');

  return `import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:go_router/go_router.dart';
import 'generated/project_manifest.dart';
${imports}

const _logPrefix = '[BuildWeaver:FlutterApp]';

final GoRouter _router = GoRouter(
  initialLocation: GeneratedProjectManifest.initialRoute,
  routes: [
${routes}
  ],
  errorBuilder: (context, state) => Scaffold(
    appBar: AppBar(title: const Text('Route Not Found')),
    body: Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Text(
          'Unable to resolve route: ${'$'}{state.uri}',
          textAlign: TextAlign.center,
        ),
      ),
    ),
  ),
);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await dotenv.load(fileName: '.env');
    debugPrint('$_logPrefix Loaded .env configuration');
  } catch (error) {
    debugPrint('$_logPrefix .env not found or failed to load, using defaults: ${'$'}error');
  }

  runApp(const GeneratedApp());
}

class GeneratedApp extends StatelessWidget {
  const GeneratedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: GeneratedProjectManifest.projectName,
      debugShowCheckedModeBanner: false,
      routerConfig: _router,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFD34E4E)),
        useMaterial3: true,
      ),
    );
  }
}
`;
};

const createAppEnvFile = (): string => `import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

const _logPrefix = '[BuildWeaver:FlutterEnv]';

class AppEnv {
  static final String apiBaseUrl = _resolveApiBaseUrl();

  static String _resolveApiBaseUrl() {
    final configured = dotenv.env['API_BASE_URL'];
    final fallback = 'http://localhost:3000';
    final raw = (configured == null || configured.trim().isEmpty)
        ? fallback
        : configured.trim();
    final normalized = raw.endsWith('/') ? raw.substring(0, raw.length - 1) : raw;
    debugPrint('$_logPrefix API_BASE_URL resolved to $normalized');
    return normalized;
  }
}
`;

const createPageDataClientFile = (): string => `import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../config/app_env.dart';

const _logPrefix = '[BuildWeaver:FlutterApi]';

class PageDataClient {
  static Future<Map<String, dynamic>> fetchPageData(String slug) async {
    final normalizedSlug = slug.startsWith('/') ? slug.substring(1) : slug;
    final uri = Uri.parse('${'$'}{AppEnv.apiBaseUrl}/api/page-data/${'$'}normalizedSlug');

    debugPrint('$_logPrefix Requesting page data from ${'$'}uri');

    final response = await http.get(
      uri,
      headers: const {
        'Accept': 'application/json',
      },
    );

    debugPrint('$_logPrefix Response status for ${'$'}normalizedSlug: ${'$'}{response.statusCode}');

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw Exception('Request failed with status ${'$'}{response.statusCode}');
    }

    final decoded = jsonDecode(response.body);
    if (decoded is Map<String, dynamic>) {
      return decoded;
    }
    if (decoded is List) {
      return {'items': decoded};
    }

    return {'value': decoded};
  }
}
`;

const createGeneratedModelsFile = (): string => `import 'dart:convert';
import 'package:flutter/foundation.dart';

const _logPrefix = '[BuildWeaver:GeneratedModels]';

class GeneratedDynamicInput {
  final String id;
  final String label;
  final String dataType;
  final String? listItemType;

  const GeneratedDynamicInput({
    required this.id,
    required this.label,
    required this.dataType,
    this.listItemType,
  });
}

class GeneratedPageSpec {
  final String id;
  final String name;
  final String route;
  final String slug;
  final String builderStateBase64;
  final List<GeneratedDynamicInput> dynamicInputs;

  const GeneratedPageSpec({
    required this.id,
    required this.name,
    required this.route,
    required this.slug,
    required this.builderStateBase64,
    required this.dynamicInputs,
  });

  Map<String, dynamic> decodeBuilderState() {
    try {
      final jsonString = utf8.decode(base64Decode(builderStateBase64));
      final decoded = jsonDecode(jsonString);
      if (decoded is Map<String, dynamic>) {
        return decoded;
      }
      debugPrint('$_logPrefix Decoded builder state is not a map for page $id');
    } catch (error) {
      debugPrint('$_logPrefix Failed to decode builder state for page $id: $error');
    }

    return {
      'root': {'id': 'root', 'props': {}, 'children': []},
      'content': [],
    };
  }
}
`;

const createPageRendererFile = (): string => `import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../data/page_data_client.dart';
import '../models/generated_models.dart';

const _logPrefix = '[BuildWeaver:FlutterRenderer]';

class GeneratedPageRenderer extends StatefulWidget {
  final GeneratedPageSpec page;

  const GeneratedPageRenderer({
    super.key,
    required this.page,
  });

  @override
  State<GeneratedPageRenderer> createState() => _GeneratedPageRendererState();
}

class _GeneratedPageRendererState extends State<GeneratedPageRenderer> {
  bool _isLoading = true;
  String? _error;
  Map<String, dynamic>? _pageData;
  late final Map<String, dynamic> _builderState;
  late final Map<String, GeneratedDynamicInput> _dynamicInputsById;

  @override
  void initState() {
    super.initState();
    _builderState = widget.page.decodeBuilderState();
    _dynamicInputsById = {
      for (final input in widget.page.dynamicInputs) input.id: input,
    };
    _loadPageData();
  }

  Future<void> _loadPageData() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final data = await PageDataClient.fetchPageData(widget.page.slug);
      if (!mounted) return;
      setState(() {
        _pageData = data;
        _isLoading = false;
      });
      debugPrint('$_logPrefix Loaded API data for page ${'$'}{widget.page.id}');
    } catch (error) {
      if (!mounted) return;
      setState(() {
        _error = error.toString();
        _isLoading = false;
      });
      debugPrint('$_logPrefix Failed to load API data for page ${'$'}{widget.page.id}: $error');
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      );
    }

    if (_error != null) {
      return Scaffold(
        appBar: AppBar(title: Text(widget.page.name)),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(Icons.error_outline, size: 48),
                const SizedBox(height: 12),
                Text(
                  'Unable to load page data for ${'$'}{widget.page.slug}',
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 8),
                Text(
                  _error!,
                  textAlign: TextAlign.center,
                  style: const TextStyle(fontSize: 12, color: Colors.black54),
                ),
                const SizedBox(height: 16),
                FilledButton(
                  onPressed: _loadPageData,
                  child: const Text('Retry'),
                )
              ],
            ),
          ),
        ),
      );
    }

    final content = _asComponentList(_builderState['content']);
    final zones = _asZoneMap(_builderState['zones']);

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.page.name),
      ),
      body: SafeArea(
        child: content.isEmpty
            ? _buildEmptyState()
            : SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: _renderComponentList(content, zones),
                ),
              ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Text(
          'No components were found for this page. Add content in BuildWeaver and regenerate.',
          textAlign: TextAlign.center,
          style: const TextStyle(color: Colors.black54),
        ),
      ),
    );
  }

  List<Widget> _renderComponentList(
    List<Map<String, dynamic>> components,
    Map<String, List<Map<String, dynamic>>> zones,
  ) {
    return components
        .map((component) => _renderComponent(component, zones, 0))
        .toList(growable: false);
  }

  Widget _renderComponent(
    Map<String, dynamic> component,
    Map<String, List<Map<String, dynamic>>> zones,
    int depth,
  ) {
    if (depth > 30) {
      debugPrint('$_logPrefix Max render depth reached, skipping component');
      return const SizedBox.shrink();
    }

    final type = component['type']?.toString() ?? 'Unknown';
    final props = _asMap(component['props']);

    final isVisible = _resolveBool(props['renderWhen'], fallback: true);
    if (!isVisible) {
      return const SizedBox.shrink();
    }

    if (type.startsWith('Library:')) {
      final definition = _asMap(props['definition']);
      if (definition.isNotEmpty) {
        final child = _renderComponent(definition, zones, depth + 1);
        return _applyStyleWrapper(props, child);
      }
      return _buildFallback(type, props, 'Library component has no definition');
    }

    switch (type) {
      case 'Section':
        return _buildSection(component, props, zones, depth);
      case 'Columns':
        return _buildColumns(component, props, zones, depth);
      case 'Heading':
        return _buildHeading(props);
      case 'Paragraph':
        return _buildParagraph(props);
      case 'Button':
        return _buildButton(props);
      case 'Image':
        return _buildImage(props);
      case 'Card':
        return _buildCard(props);
      case 'List':
        return _buildList(component, props, zones, depth);
      case 'Divider':
        return _buildDivider(props);
      case 'Spacer':
        return _buildSpacer(props);
      case 'Conditional':
        return _buildConditional(component, props, zones, depth);
      default:
        return _buildFallback(type, props, 'Unsupported component type');
    }
  }

  Widget _buildSection(
    Map<String, dynamic> component,
    Map<String, dynamic> props,
    Map<String, List<Map<String, dynamic>>> zones,
    int depth,
  ) {
    final eyebrow = _resolveString(props['eyebrow']);
    final heading = _resolveString(props['heading']);
    final subheading = _resolveString(props['subheading']);
    final description = _resolveString(props['description']);
    final backgroundImage = _resolveString(props['backgroundImage']);

    final slotChildren = _resolveSlotChildren(component, 'contentSlot', zones);
    final renderedSlotChildren = _renderComponentList(slotChildren, zones);

    final contentChildren = <Widget>[];
    if (eyebrow.isNotEmpty) {
      contentChildren.add(Text(
        eyebrow,
        style: _buildTextStyle(props).copyWith(
          fontSize: 12,
          letterSpacing: 2,
          color: const Color(0xFFD34E4E),
        ),
      ));
      contentChildren.add(const SizedBox(height: 8));
    }
    if (heading.isNotEmpty) {
      contentChildren.add(Text(
        heading,
        textAlign: _resolveTextAlign(props),
        style: _buildTextStyle(props).copyWith(
          fontSize: _parseDimension(_resolveString(props['fontSize']), horizontal: true) ?? 36,
          fontWeight: _resolveFontWeight(_resolveString(props['fontWeight'])) ?? FontWeight.w600,
        ),
      ));
      contentChildren.add(const SizedBox(height: 8));
    }
    if (subheading.isNotEmpty) {
      contentChildren.add(Text(
        subheading,
        textAlign: _resolveTextAlign(props),
        style: _buildTextStyle(props).copyWith(
          fontSize: _parseDimension(_resolveString(props['fontSize']), horizontal: true) ?? 18,
        ),
      ));
      contentChildren.add(const SizedBox(height: 8));
    }
    if (description.isNotEmpty) {
      contentChildren.add(Text(
        description,
        textAlign: _resolveTextAlign(props),
        style: _buildTextStyle(props).copyWith(fontSize: 16),
      ));
    }

    if (renderedSlotChildren.isNotEmpty) {
      if (contentChildren.isNotEmpty) {
        contentChildren.add(const SizedBox(height: 20));
      }
      contentChildren.addAll(renderedSlotChildren);
    }

    if (contentChildren.isEmpty) {
      contentChildren.add(
        const Text('Section has no content yet.'),
      );
    }

    final inner = Stack(
      children: [
        if (backgroundImage.isNotEmpty)
          Positioned.fill(
            child: Opacity(
              opacity: 0.16,
              child: Image.network(
                backgroundImage,
                fit: BoxFit.cover,
                errorBuilder: (_, __, ___) => const SizedBox.shrink(),
              ),
            ),
          ),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: contentChildren,
        )
      ],
    );

    return _applyStyleWrapper(props, inner);
  }

  Widget _buildColumns(
    Map<String, dynamic> component,
    Map<String, dynamic> props,
    Map<String, List<Map<String, dynamic>>> zones,
    int depth,
  ) {
    final layout = _resolveString(props['layout'], fallback: 'equal');
    final stackAt = _resolveString(props['stackAt'], fallback: 'md');

    final leftChildren = _resolveSlotChildren(component, 'left', zones);
    final rightChildren = _resolveSlotChildren(component, 'right', zones);

    final leftWidget = Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: _renderComponentList(leftChildren, zones),
    );
    final rightWidget = Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: _renderComponentList(rightChildren, zones),
    );

    final ratio = _resolveColumnsRatio(layout);
    final viewportWidth = MediaQuery.of(context).size.width;
    final shouldStack = (stackAt == 'md' && viewportWidth < 768) ||
        (stackAt == 'lg' && viewportWidth < 1024);

    final gap = _parseDimension(_resolveString(props['gap']), horizontal: true) ?? 24;

    Widget content;
    if (shouldStack) {
      content = Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          leftWidget,
          SizedBox(height: gap),
          rightWidget,
        ],
      );
    } else {
      content = Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(flex: ratio.$1, child: leftWidget),
          SizedBox(width: gap),
          Expanded(flex: ratio.$2, child: rightWidget),
        ],
      );
    }

    return _applyStyleWrapper(props, content);
  }

  Widget _buildHeading(Map<String, dynamic> props) {
    final content = _resolveString(props['content']);
    final size = _resolveString(props['size'], fallback: 'h2');
    final sizeMap = <String, double>{
      'h1': 42,
      'h2': 34,
      'h3': 28,
      'h4': 22,
    };

    final textWidget = Text(
      content,
      textAlign: _resolveTextAlign(props),
      style: _buildTextStyle(props).copyWith(
        fontSize: _parseDimension(_resolveString(props['fontSize']), horizontal: true) ??
            sizeMap[size] ??
            34,
        fontWeight: _resolveFontWeight(_resolveString(props['fontWeight'])) ?? FontWeight.w600,
      ),
    );

    return _applyStyleWrapper(props, textWidget);
  }

  Widget _buildParagraph(Map<String, dynamic> props) {
    final content = _resolveString(props['content']);
    final textWidget = Text(
      content,
      textAlign: _resolveTextAlign(props),
      style: _buildTextStyle(props).copyWith(
        fontSize: _parseDimension(_resolveString(props['fontSize']), horizontal: true) ?? 16,
        height: _resolveLineHeight(_resolveString(props['lineHeight'])) ?? 1.6,
      ),
    );
    return _applyStyleWrapper(props, textWidget);
  }

  Widget _buildButton(Map<String, dynamic> props) {
    final label = _resolveString(props['label'], fallback: 'Button');
    final variant = _resolveString(props['variant'], fallback: 'primary');
    final href = _resolveString(props['href']);

    final textStyle = _buildTextStyle(props).copyWith(
      fontWeight: _resolveFontWeight(_resolveString(props['fontWeight'])) ?? FontWeight.w600,
    );

    final onPressed = href.isEmpty ? () {} : () => _openHref(href);

    Widget button;
    if (variant == 'ghost') {
      button = OutlinedButton(
        onPressed: onPressed,
        child: Text(label, style: textStyle),
      );
    } else if (variant == 'link') {
      button = TextButton(
        onPressed: onPressed,
        child: Text(label, style: textStyle.copyWith(decoration: TextDecoration.underline)),
      );
    } else {
      button = ElevatedButton(
        onPressed: onPressed,
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFFDDC57A),
          foregroundColor: const Color(0xFF1A1A2E),
        ),
        child: Text(label, style: textStyle),
      );
    }

    return _applyStyleWrapper(props, button);
  }

  Widget _buildImage(Map<String, dynamic> props) {
    final src = _resolveString(props['src']);
    final caption = _resolveString(props['caption']);
    final alt = _resolveString(props['alt']);
    final objectFit = _resolveString(props['objectFit'], fallback: 'cover');
    final aspectRatio = _parseAspectRatio(_resolveString(props['aspectRatio']));

    final boxFit = _resolveBoxFit(objectFit);
    Widget imageWidget = src.isEmpty
        ? Container(
            color: const Color(0xFFF4F4F5),
            alignment: Alignment.center,
            child: const Text('Image URL missing'),
          )
        : Image.network(
            src,
            fit: boxFit,
            semanticLabel: alt.isEmpty ? null : alt,
            errorBuilder: (_, __, ___) => Container(
              color: const Color(0xFFF4F4F5),
              alignment: Alignment.center,
              child: const Text('Failed to load image'),
            ),
          );

    if (aspectRatio != null && aspectRatio > 0) {
      imageWidget = AspectRatio(
        aspectRatio: aspectRatio,
        child: imageWidget,
      );
    }

    final columnChildren = <Widget>[imageWidget];
    if (caption.isNotEmpty) {
      columnChildren.add(const SizedBox(height: 8));
      columnChildren.add(
        Text(
          caption,
          style: _buildTextStyle(props).copyWith(fontSize: 12, color: Colors.black54),
        ),
      );
    }

    return _applyStyleWrapper(
      props,
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: columnChildren,
      ),
    );
  }

  Widget _buildCard(Map<String, dynamic> props) {
    final eyebrow = _resolveString(props['eyebrow']);
    final heading = _resolveString(props['heading']);
    final body = _resolveString(props['content']);
    final imageUrl = _resolveString(props['imageUrl']);
    final actionLabel = _resolveString(props['actionLabel']);
    final actionHref = _resolveString(props['actionHref']);

    final children = <Widget>[];

    if (imageUrl.isNotEmpty) {
      children.add(
        ClipRRect(
          borderRadius: BorderRadius.circular(12),
          child: Image.network(
            imageUrl,
            fit: BoxFit.cover,
            errorBuilder: (_, __, ___) => const SizedBox.shrink(),
          ),
        ),
      );
      children.add(const SizedBox(height: 12));
    }

    if (eyebrow.isNotEmpty) {
      children.add(
        Text(
          eyebrow,
          style: _buildTextStyle(props).copyWith(
            fontSize: 12,
            letterSpacing: 1,
            color: const Color(0xFFD34E4E),
          ),
        ),
      );
      children.add(const SizedBox(height: 4));
    }

    if (heading.isNotEmpty) {
      children.add(
        Text(
          heading,
          style: _buildTextStyle(props).copyWith(fontSize: 24, fontWeight: FontWeight.w600),
        ),
      );
      children.add(const SizedBox(height: 8));
    }

    if (body.isNotEmpty) {
      children.add(
        Text(
          body,
          style: _buildTextStyle(props).copyWith(fontSize: 16),
        ),
      );
      children.add(const SizedBox(height: 12));
    }

    if (actionLabel.isNotEmpty) {
      children.add(
        InkWell(
          onTap: actionHref.isEmpty ? null : () => _openHref(actionHref),
          child: Text(
            actionLabel,
            style: _buildTextStyle(props).copyWith(
              color: const Color(0xFFD34E4E),
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      );
    }

    return _applyStyleWrapper(
      props,
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: children,
      ),
    );
  }

  Widget _buildList(
    Map<String, dynamic> component,
    Map<String, dynamic> props,
    Map<String, List<Map<String, dynamic>>> zones,
    int depth,
  ) {
    final variant = _resolveString(props['variant'], fallback: 'bullet');
    final renderMode = _resolveString(props['renderMode'], fallback: 'builtIn');
    final dynamicEntries = _resolveDynamicListEntries(props['dataSource']);
    final manualEntries = _resolveManualListEntries(props['items']);
    final entries = dynamicEntries.isNotEmpty ? dynamicEntries : manualEntries;

    if (renderMode == 'custom') {
      final slotChildren = _resolveSlotChildren(component, 'customItemSlot', zones);
      if (slotChildren.isEmpty) {
        return _applyStyleWrapper(
          props,
          const Text('Add components in custom item slot to render list entries.'),
        );
      }

      if (entries.isEmpty) {
        return _applyStyleWrapper(
          props,
          const Text('Connect list data or add manual items to render custom entries.'),
        );
      }

      final itemWidgets = <Widget>[];
      for (final _ in entries) {
        itemWidgets.add(
          Container(
            margin: const EdgeInsets.only(bottom: 12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: _renderComponentList(slotChildren, zones),
            ),
          ),
        );
      }

      return _applyStyleWrapper(
        props,
        Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: itemWidgets,
        ),
      );
    }

    final widgets = <Widget>[];
    for (var i = 0; i < entries.length; i += 1) {
      final entry = entries[i];
      if (variant == 'plain') {
        widgets.add(
          Container(
            margin: const EdgeInsets.only(bottom: 10),
            padding: const EdgeInsets.only(left: 12),
            decoration: const BoxDecoration(
              border: Border(left: BorderSide(color: Color(0xFFDDC57A), width: 2)),
            ),
            child: _buildListEntryText(entry),
          ),
        );
      } else {
        final marker = variant == 'numbered' ? '${'$'}{i + 1}.' : '•';
        widgets.add(
          Padding(
            padding: const EdgeInsets.only(bottom: 8),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(width: 22, child: Text(marker)),
                Expanded(child: _buildListEntryText(entry)),
              ],
            ),
          ),
        );
      }
    }

    if (widgets.isEmpty) {
      widgets.add(const Text('List has no items yet.'));
    }

    return _applyStyleWrapper(
      props,
      Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: widgets,
      ),
    );
  }

  Widget _buildListEntryText(_ListEntry entry) {
    final children = <Widget>[];
    children.add(
      Text(
        entry.text,
        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
      ),
    );
    if (entry.description != null && entry.description!.isNotEmpty) {
      children.add(
        Text(
          entry.description!,
          style: const TextStyle(fontSize: 13, color: Colors.black54),
        ),
      );
    }
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: children,
    );
  }

  Widget _buildDivider(Map<String, dynamic> props) {
    final thickness =
        _parseDimension(_resolveString(props['borderWidth']), horizontal: true) ?? 1;
    final color = _parseColor(_resolveString(props['borderColor'])) ??
        const Color(0xFFE5E7EB);

    return _applyStyleWrapper(
      props,
      Divider(
        thickness: thickness,
        color: color,
        height: thickness,
      ),
      includePadding: false,
    );
  }

  Widget _buildSpacer(Map<String, dynamic> props) {
    final height =
        _parseDimension(_resolveString(props['height'], fallback: '48px'), horizontal: false) ?? 48;

    return _applyStyleWrapper(
      props,
      SizedBox(height: height),
      includePadding: false,
    );
  }

  Widget _buildConditional(
    Map<String, dynamic> component,
    Map<String, dynamic> props,
    Map<String, List<Map<String, dynamic>>> zones,
    int depth,
  ) {
    final activeCaseKey = _resolveString(props['activeCaseKey']);
    final casesRaw = props['cases'];
    if (casesRaw is! List || casesRaw.isEmpty) {
      return _applyStyleWrapper(
        props,
        const Text('Conditional has no case definitions.'),
      );
    }

    final normalizedCases = <_ConditionalCase>[];
    for (var index = 0; index < casesRaw.length; index += 1) {
      final caseMap = casesRaw[index] as Map<String, dynamic>? ?? <String, Object?>{};
      final key = _sanitizeCaseKey(
        caseMap['caseKey']?.toString(),
        fallback: 'case-${'$'}{index + 1}',
      );
      final label = caseMap['label']?.toString() ?? 'Case ${'$'}{index + 1}';
      final slotInline = _asComponentList(caseMap['slot']);
      final slotFromZone = _resolveCaseSlotChildren(component, index, zones);
      final slotChildren = slotInline.isNotEmpty ? slotInline : slotFromZone;
      normalizedCases.add(_ConditionalCase(key: key, label: label, children: slotChildren));
    }

    final selected = normalizedCases.firstWhere(
      (entry) => entry.key == activeCaseKey,
      orElse: () => normalizedCases.first,
    );

    final renderedChildren = _renderComponentList(selected.children, zones);
    if (renderedChildren.isEmpty) {
      return _applyStyleWrapper(
        props,
        Text('No content assigned to case "${'$'}{selected.label}".'),
      );
    }

    return _applyStyleWrapper(
      props,
      Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: renderedChildren,
      ),
    );
  }

  Widget _buildFallback(String type, Map<String, dynamic> props, String reason) {
    debugPrint('$_logPrefix $reason: $type');
    return _applyStyleWrapper(
      props,
      Text(
        'Unsupported component: $type',
        style: const TextStyle(fontSize: 12, color: Colors.black54),
      ),
    );
  }

  Widget _applyStyleWrapper(
    Map<String, dynamic> props,
    Widget child, {
    bool includePadding = true,
  }) {
    final margin = _resolveEdgeInsets(props, allKey: 'margin', xKey: 'marginX', yKey: 'marginY');
    final padding = includePadding
        ? _resolveEdgeInsets(props, allKey: 'padding', xKey: 'paddingX', yKey: 'paddingY')
        : null;
    final width = _parseDimension(_resolveString(props['width']), horizontal: true);
    final maxWidth = _parseDimension(_resolveString(props['maxWidth']), horizontal: true);
    final minHeight = _parseDimension(_resolveString(props['minHeight']), horizontal: false);
    final opacity = _resolveOpacity(_resolveString(props['opacity'], fallback: '1'));

    final decoration = _buildDecoration(props);
    final constraints = _buildConstraints(maxWidth: maxWidth, minHeight: minHeight);

    Widget current = Container(
      width: width,
      margin: margin,
      padding: padding,
      constraints: constraints,
      decoration: decoration,
      child: child,
    );

    if (opacity < 1) {
      current = Opacity(opacity: opacity, child: current);
    }

    return current;
  }

  BoxConstraints? _buildConstraints({double? maxWidth, double? minHeight}) {
    if (maxWidth == null && minHeight == null) {
      return null;
    }

    return BoxConstraints(
      maxWidth: maxWidth ?? double.infinity,
      minHeight: minHeight ?? 0,
    );
  }

  BoxDecoration? _buildDecoration(Map<String, dynamic> props) {
    final backgroundValue = _resolveString(props['backgroundColor']);
    final gradient = _parseGradient(backgroundValue);
    final color = gradient == null ? _parseColor(backgroundValue) : null;

    final borderWidth = _parseDimension(_resolveString(props['borderWidth']), horizontal: true);
    final borderColor = _parseColor(_resolveString(props['borderColor'])) ??
        const Color(0x11000000);

    final borderRadiusValue = _parseDimension(_resolveString(props['borderRadius']), horizontal: true);
    final borderRadius = borderRadiusValue != null
        ? BorderRadius.circular(borderRadiusValue)
        : null;

    final shadows = _parseBoxShadows(_resolveString(props['boxShadow']));

    final hasDecoration =
        gradient != null ||
        color != null ||
        (borderWidth != null && borderWidth > 0) ||
        borderRadius != null ||
        shadows.isNotEmpty;

    if (!hasDecoration) {
      return null;
    }

    return BoxDecoration(
      color: color,
      gradient: gradient,
      border: borderWidth != null && borderWidth > 0
          ? Border.all(width: borderWidth, color: borderColor)
          : null,
      borderRadius: borderRadius,
      boxShadow: shadows.isEmpty ? null : shadows,
    );
  }

  List<BoxShadow> _parseBoxShadows(String raw) {
    if (raw.trim().isEmpty) {
      return const <BoxShadow>[];
    }

    final pattern = RegExp(
      r'(-?\\d+(?:\\.\\d+)?)px\\s+(-?\\d+(?:\\.\\d+)?)px\\s+(\\d+(?:\\.\\d+)?)px\\s+(.+)',
      caseSensitive: false,
    );
    final match = pattern.firstMatch(raw.trim());
    if (match == null) {
      return const <BoxShadow>[];
    }

    final dx = double.tryParse(match.group(1) ?? '0') ?? 0;
    final dy = double.tryParse(match.group(2) ?? '0') ?? 0;
    final blur = double.tryParse(match.group(3) ?? '0') ?? 0;
    final color = _parseColor((match.group(4) ?? '').trim()) ??
        const Color(0x22000000);

    return [
      BoxShadow(
        color: color,
        offset: Offset(dx, dy),
        blurRadius: blur,
      ),
    ];
  }

  Gradient? _parseGradient(String value) {
    final trimmed = value.trim();
    if (trimmed.isEmpty) {
      return null;
    }

    if (trimmed.startsWith('linear-gradient(') && trimmed.endsWith(')')) {
      final inside = trimmed.substring('linear-gradient('.length, trimmed.length - 1);
      final args = _splitGradientArgs(inside);
      if (args.length < 2) {
        return null;
      }

      var angle = 90.0;
      var stopStartIndex = 0;
      final maybeAngle = args[0].trim();
      if (maybeAngle.endsWith('deg')) {
        angle = double.tryParse(maybeAngle.replaceAll('deg', '').trim()) ?? 90;
        stopStartIndex = 1;
      }

      final parsedStops = <_GradientStop>[];
      for (final part in args.skip(stopStartIndex)) {
        final stop = _parseGradientStop(part);
        if (stop != null) {
          parsedStops.add(stop);
        }
      }

      if (parsedStops.length < 2) {
        return null;
      }

      final colors = parsedStops.map((stop) => stop.color).toList(growable: false);
      final stops = _normalizeStops(parsedStops);

      final radians = (angle - 90) * math.pi / 180;
      final begin = Alignment(-math.cos(radians), -math.sin(radians));
      final end = Alignment(math.cos(radians), math.sin(radians));

      return LinearGradient(
        begin: begin,
        end: end,
        colors: colors,
        stops: stops,
      );
    }

    if (trimmed.startsWith('radial-gradient(') && trimmed.endsWith(')')) {
      final inside = trimmed.substring('radial-gradient('.length, trimmed.length - 1);
      final args = _splitGradientArgs(inside);
      final effective = args.isNotEmpty && args.first.trim().startsWith('circle')
          ? args.skip(1).toList(growable: false)
          : args;

      final parsedStops = <_GradientStop>[];
      for (final part in effective) {
        final stop = _parseGradientStop(part);
        if (stop != null) {
          parsedStops.add(stop);
        }
      }

      if (parsedStops.length < 2) {
        return null;
      }

      return RadialGradient(
        colors: parsedStops.map((stop) => stop.color).toList(growable: false),
        stops: _normalizeStops(parsedStops),
      );
    }

    return null;
  }

  List<String> _splitGradientArgs(String value) {
    final segments = <String>[];
    final buffer = StringBuffer();
    var depth = 0;

    for (var i = 0; i < value.length; i += 1) {
      final char = value[i];
      if (char == ',' && depth == 0) {
        final segment = buffer.toString().trim();
        if (segment.isNotEmpty) {
          segments.add(segment);
        }
        buffer.clear();
        continue;
      }

      if (char == '(') {
        depth += 1;
      } else if (char == ')' && depth > 0) {
        depth -= 1;
      }
      buffer.write(char);
    }

    final tail = buffer.toString().trim();
    if (tail.isNotEmpty) {
      segments.add(tail);
    }
    return segments;
  }

  _GradientStop? _parseGradientStop(String raw) {
    final pattern = RegExp(r'^(.*?)(?:\\s+([0-9]*\\.?[0-9]+)%?)?$');
    final match = pattern.firstMatch(raw.trim());
    if (match == null) {
      return null;
    }

    final colorToken = (match.group(1) ?? '').trim();
    final color = _parseColor(colorToken);
    if (color == null) {
      return null;
    }

    final stopPercent = double.tryParse((match.group(2) ?? '').trim());
    return _GradientStop(
      color: color,
      stop: stopPercent == null ? null : (stopPercent / 100).clamp(0, 1).toDouble(),
    );
  }

  List<double> _normalizeStops(List<_GradientStop> stops) {
    if (stops.isEmpty) {
      return const <double>[];
    }
    final allHaveStops = stops.every((entry) => entry.stop != null);
    if (allHaveStops) {
      return stops.map((entry) => entry.stop!).toList(growable: false);
    }

    final result = <double>[];
    final denominator = (stops.length - 1).clamp(1, 9999).toDouble();
    for (var i = 0; i < stops.length; i += 1) {
      result.add(i / denominator);
    }
    return result;
  }

  TextStyle _buildTextStyle(Map<String, dynamic> props) {
    final color = _parseColor(_resolveString(props['textColor'])) ??
        const Color(0xFF111827);
    final fontSize = _parseDimension(_resolveString(props['fontSize']), horizontal: true);
    final fontWeight = _resolveFontWeight(_resolveString(props['fontWeight']));
    final lineHeight = _resolveLineHeight(_resolveString(props['lineHeight']));

    return TextStyle(
      color: color,
      fontSize: fontSize,
      fontWeight: fontWeight,
      height: lineHeight,
    );
  }

  TextAlign _resolveTextAlign(Map<String, dynamic> props) {
    final value = _resolveString(props['textAlign']);
    switch (value) {
      case 'center':
        return TextAlign.center;
      case 'right':
        return TextAlign.right;
      case 'justify':
        return TextAlign.justify;
      default:
        return TextAlign.left;
    }
  }

  FontWeight? _resolveFontWeight(String value) {
    final parsed = int.tryParse(value.trim());
    if (parsed == null) {
      return null;
    }
    if (parsed >= 700) return FontWeight.w700;
    if (parsed >= 600) return FontWeight.w600;
    if (parsed >= 500) return FontWeight.w500;
    if (parsed >= 400) return FontWeight.w400;
    return FontWeight.w300;
  }

  double? _resolveLineHeight(String value) {
    final parsed = double.tryParse(value.trim());
    if (parsed == null || parsed <= 0) {
      return null;
    }
    return parsed;
  }

  BoxFit _resolveBoxFit(String value) {
    switch (value) {
      case 'contain':
        return BoxFit.contain;
      case 'fill':
        return BoxFit.fill;
      default:
        return BoxFit.cover;
    }
  }

  (int, int) _resolveColumnsRatio(String layout) {
    switch (layout) {
      case 'wideLeft':
        return (3, 2);
      case 'wideRight':
        return (2, 3);
      default:
        return (1, 1);
    }
  }

  double _resolveOpacity(String value) {
    final parsed = double.tryParse(value.trim()) ?? 1;
    return parsed.clamp(0, 1).toDouble();
  }

  EdgeInsets _resolveEdgeInsets(
    Map<String, dynamic> props, {
    required String allKey,
    required String xKey,
    required String yKey,
  }) {
    final all = _parseDimension(_resolveString(props[allKey]), horizontal: true) ?? 0;
    final x = _parseDimension(_resolveString(props[xKey]), horizontal: true);
    final y = _parseDimension(_resolveString(props[yKey]), horizontal: false);

    final horizontal = x ?? all;
    final vertical = y ?? all;
    return EdgeInsets.fromLTRB(horizontal, vertical, horizontal, vertical);
  }

  double? _parseAspectRatio(String value) {
    final normalized = value.trim();
    if (normalized.isEmpty) {
      return null;
    }
    if (normalized.contains('/')) {
      final parts = normalized.split('/');
      if (parts.length == 2) {
        final left = double.tryParse(parts[0].trim());
        final right = double.tryParse(parts[1].trim());
        if (left != null && right != null && right != 0) {
          return left / right;
        }
      }
    }
    return double.tryParse(normalized);
  }

  double? _parseDimension(String value, {required bool horizontal}) {
    final raw = value.trim().toLowerCase();
    if (raw.isEmpty || raw == 'auto') {
      return null;
    }

    final viewport = MediaQuery.of(context).size;
    final axisExtent = horizontal ? viewport.width : viewport.height;

    if (raw.endsWith('px')) {
      return double.tryParse(raw.replaceAll('px', '').trim());
    }
    if (raw.endsWith('rem')) {
      final parsed = double.tryParse(raw.replaceAll('rem', '').trim());
      return parsed == null ? null : parsed * 16;
    }
    if (raw.endsWith('%')) {
      final parsed = double.tryParse(raw.replaceAll('%', '').trim());
      return parsed == null ? null : axisExtent * (parsed / 100);
    }
    if (raw.endsWith('vw')) {
      final parsed = double.tryParse(raw.replaceAll('vw', '').trim());
      return parsed == null ? null : viewport.width * (parsed / 100);
    }
    if (raw.endsWith('vh')) {
      final parsed = double.tryParse(raw.replaceAll('vh', '').trim());
      return parsed == null ? null : viewport.height * (parsed / 100);
    }
    return double.tryParse(raw);
  }

  Color? _parseColor(String value) {
    final raw = value.trim();
    if (raw.isEmpty) {
      return null;
    }
    if (raw.toLowerCase() == 'transparent') {
      return Colors.transparent;
    }

    final hex = raw.startsWith('#') ? raw.substring(1) : raw;
    if (RegExp(r'^[0-9a-fA-F]{3}$').hasMatch(hex)) {
      final expanded = hex.split('').map((char) => '$char$char').join();
      return Color(int.parse('ff$expanded', radix: 16));
    }
    if (RegExp(r'^[0-9a-fA-F]{6}$').hasMatch(hex)) {
      return Color(int.parse('ff$hex', radix: 16));
    }
    if (RegExp(r'^[0-9a-fA-F]{8}$').hasMatch(hex)) {
      return Color(int.parse(hex, radix: 16));
    }

    final rgbPattern = RegExp(
      r'^rgba?\\(\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3})\\s*,\\s*(\\d{1,3})(?:\\s*,\\s*(0|1|0?\\.\\d+))?\\s*\\)$',
      caseSensitive: false,
    );
    final match = rgbPattern.firstMatch(raw);
    if (match != null) {
      final r = (int.tryParse(match.group(1) ?? '0') ?? 0).clamp(0, 255);
      final g = (int.tryParse(match.group(2) ?? '0') ?? 0).clamp(0, 255);
      final b = (int.tryParse(match.group(3) ?? '0') ?? 0).clamp(0, 255);
      final alphaDouble = double.tryParse(match.group(4) ?? '1') ?? 1;
      final alpha = (alphaDouble.clamp(0, 1) * 255).round().clamp(0, 255);
      return Color.fromARGB(alpha, r, g, b);
    }

    return null;
  }

  Future<void> _openHref(String href) async {
    final uri = Uri.tryParse(href);
    if (uri == null) {
      debugPrint('$_logPrefix Invalid href: $href');
      return;
    }

    final opened = await launchUrl(uri, mode: LaunchMode.externalApplication);
    if (!opened) {
      debugPrint('$_logPrefix Could not open URL: $href');
    }
  }

  String _resolveString(Object? value, {String fallback = ''}) {
    final resolved = _resolveDynamicValue(value);
    if (resolved == null) {
      return fallback;
    }
    if (resolved is String) {
      return resolved;
    }
    return resolved.toString();
  }

  bool _resolveBool(Object? value, {required bool fallback}) {
    final resolved = _resolveDynamicValue(value);
    if (resolved is bool) {
      return resolved;
    }
    if (resolved is String) {
      final normalized = resolved.trim().toLowerCase();
      if (normalized == 'true' || normalized == '1' || normalized == 'yes') {
        return true;
      }
      if (normalized == 'false' || normalized == '0' || normalized == 'no') {
        return false;
      }
    }
    return fallback;
  }

  Object? _resolveDynamicValue(Object? value) {
    if (value is Map && value['__bwDynamicBinding'] == true) {
      final bindingId = value['bindingId']?.toString();
      if (bindingId == null || bindingId.isEmpty) {
        return value['fallback'];
      }

      final dynamicInput = _dynamicInputsById[bindingId];
      final key = _toPropertyKey(dynamicInput?.label ?? bindingId);
      var current = _pageData?[key];

      final path = value['propertyPath'];
      if (path is List) {
        current = _resolvePropertyPath(current, path);
      }

      if (current == null) {
        return value['fallback'];
      }
      return current;
    }
    return value;
  }

  Object? _resolvePropertyPath(Object? source, List<dynamic> path) {
    var current = source;
    for (final segment in path) {
      if (current == null) {
        return null;
      }
      if (current is Map) {
        current = current[segment.toString()];
        continue;
      }
      if (current is List) {
        final index = int.tryParse(segment.toString());
        if (index == null || index < 0 || index >= current.length) {
          return null;
        }
        current = current[index];
        continue;
      }
      return null;
    }
    return current;
  }

  String _toPropertyKey(String label) {
    final cleaned = label
        .replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'(^_|_$)+'), '');
    if (cleaned.isEmpty) {
      return 'value';
    }
    if (RegExp(r'^\\d').hasMatch(cleaned)) {
      return '_$cleaned';
    }
    return cleaned;
  }

  Map<String, dynamic> _asMap(Object? value) {
    if (value is Map<String, dynamic>) {
      return value;
    }
    if (value is Map) {
      return value.map((key, dynamic mapValue) => MapEntry(key.toString(), mapValue));
    }
    return <String, dynamic>{};
  }

  List<Map<String, dynamic>> _asComponentList(Object? value) {
    if (value is! List) {
      return const <Map<String, dynamic>>[];
    }

    return value
        .whereType<Object>()
        .map(_asMap)
        .where((entry) => entry.containsKey('type'))
        .toList(growable: false);
  }

  Map<String, List<Map<String, dynamic>>> _asZoneMap(Object? value) {
    if (value is! Map) {
      return const <String, List<Map<String, dynamic>>>{};
    }

    final zones = <String, List<Map<String, dynamic>>>{};
    value.forEach((key, dynamic zoneValue) {
      zones[key.toString()] = _asComponentList(zoneValue);
    });
    return zones;
  }

  List<Map<String, dynamic>> _resolveSlotChildren(
    Map<String, dynamic> component,
    String slotName,
    Map<String, List<Map<String, dynamic>>> zones,
  ) {
    final props = _asMap(component['props']);
    final inlineChildren = _asComponentList(props[slotName]);
    if (inlineChildren.isNotEmpty) {
      return inlineChildren;
    }

    final componentId = props['id']?.toString();
    if (componentId == null || componentId.isEmpty) {
      return const <Map<String, dynamic>>[];
    }

    final key = '$componentId:$slotName';
    return zones[key] ?? const <Map<String, dynamic>>[];
  }

  List<Map<String, dynamic>> _resolveCaseSlotChildren(
    Map<String, dynamic> component,
    int caseIndex,
    Map<String, List<Map<String, dynamic>>> zones,
  ) {
    final props = _asMap(component['props']);
    final componentId = props['id']?.toString();
    if (componentId == null || componentId.isEmpty) {
      return const <Map<String, dynamic>>[];
    }
    final zoneKey = '$componentId:cases-$caseIndex-slot';
    return zones[zoneKey] ?? const <Map<String, dynamic>>[];
  }

  String _sanitizeCaseKey(String? value, {required String fallback}) {
    final raw = (value ?? '').trim();
    if (raw.isEmpty) {
      return fallback;
    }
    final normalized = raw
        .toLowerCase()
        .replaceAll(RegExp(r'\\s+'), '-')
        .replaceAll(RegExp(r'[^a-z0-9_-]+'), '-')
        .replaceAll(RegExp(r'-+'), '-')
        .replaceAll(RegExp(r'(^-|-$)+'), '');
    return normalized.isEmpty ? fallback : normalized;
  }

  List<_ListEntry> _resolveManualListEntries(Object? value) {
    final entries = <_ListEntry>[];
    if (value is! List) {
      return entries;
    }
    for (final item in value) {
      final map = _asMap(item);
      final text = _resolveString(map['text'], fallback: 'List item');
      final description = _resolveString(map['description']);
      entries.add(_ListEntry(text: text, description: description.isEmpty ? null : description));
    }
    return entries;
  }

  List<_ListEntry> _resolveDynamicListEntries(Object? bindingValue) {
    final resolved = _resolveDynamicValue(bindingValue);
    if (resolved is! List) {
      return const <_ListEntry>[];
    }

    final entries = <_ListEntry>[];
    for (final item in resolved) {
      if (item == null) {
        entries.add(const _ListEntry(text: 'Item'));
      } else if (item is String || item is num || item is bool) {
        entries.add(_ListEntry(text: item.toString()));
      } else if (item is List) {
        entries.add(_ListEntry(text: item.map((entry) => '$entry').join(', ')));
      } else if (item is Map) {
        final map = _asMap(item);
        final text = map['title']?.toString() ??
            map['name']?.toString() ??
            map['label']?.toString() ??
            map['heading']?.toString() ??
            map['text']?.toString() ??
            'Item';
        final description = map['description']?.toString() ??
            map['summary']?.toString() ??
            map['body']?.toString() ??
            map['content']?.toString();
        entries.add(_ListEntry(text: text, description: description));
      } else {
        entries.add(_ListEntry(text: item.toString()));
      }
    }
    return entries;
  }
}

class _ConditionalCase {
  final String key;
  final String label;
  final List<Map<String, dynamic>> children;

  const _ConditionalCase({
    required this.key,
    required this.label,
    required this.children,
  });
}

class _ListEntry {
  final String text;
  final String? description;

  const _ListEntry({
    required this.text,
    this.description,
  });
}

class _GradientStop {
  final Color color;
  final double? stop;

  const _GradientStop({
    required this.color,
    required this.stop,
  });
}
`;

const createProjectManifestFile = (
  project: ProjectIR,
  pages: FlutterPageModel[]
): string => {
  const pageEntries = pages
    .map((page) => {
      const dynamicInputs = page.dynamicInputs
        .map(
          (input) => `        GeneratedDynamicInput(
          id: '${escapeDartString(input.id)}',
          label: '${escapeDartString(input.label)}',
          dataType: '${escapeDartString(input.dataType)}',
          listItemType: ${
            input.listItemType
              ? `'${escapeDartString(input.listItemType)}'`
              : 'null'
          },
        )`
        )
        .join(',\n');

      return `    GeneratedPageSpec(
      id: '${escapeDartString(page.id)}',
      name: '${escapeDartString(page.name)}',
      route: '${escapeDartString(page.route)}',
      slug: '${escapeDartString(page.slug)}',
      builderStateBase64: '${page.builderStateBase64}',
      dynamicInputs: [
${dynamicInputs}
      ],
    )`;
    })
    .join(',\n');

  return `import '../models/generated_models.dart';

class GeneratedProjectManifest {
  static const String projectName = '${escapeDartString(project.metadata.name)}';

  static const List<GeneratedPageSpec> pages = [
${pageEntries}
  ];

  static String get initialRoute => pages.isNotEmpty ? pages.first.route : '/';

  static GeneratedPageSpec pageById(String id) {
    for (final page in pages) {
      if (page.id == id) {
        return page;
      }
    }
    return pages.first;
  }
}
`;
};

const createPageFile = (page: FlutterPageModel): string => `import 'package:flutter/material.dart';
import '../generated/project_manifest.dart';
import '../render/page_renderer.dart';

class ${page.className} extends StatelessWidget {
  const ${page.className}({super.key});

  @override
  Widget build(BuildContext context) {
    return GeneratedPageRenderer(
      page: GeneratedProjectManifest.pageById('${escapeDartString(page.id)}'),
    );
  }
}
`;

const createMetadataFile = (): string => `# Generated by BuildWeaver Flutter adapter
version:
  revision: generated
  channel: stable
project_type: app
`;

const buildFlutterFiles = (project: ProjectIR): GeneratedFile[] => {
  const pages = buildPageModels(project);

  console.info(`${LOG_PREFIX} Building Flutter project files`, {
    project: project.metadata.name,
    routes: pages.map((page) => page.route),
    pageCount: pages.length
  });

  const files: GeneratedFile[] = [
    { path: 'pubspec.yaml', contents: createPubspec(project) },
    { path: 'analysis_options.yaml', contents: createAnalysisOptions() },
    { path: '.gitignore', contents: createGitIgnore() },
    { path: '.env', contents: createEnvFile() },
    { path: '.env.example', contents: createEnvFile() },
    { path: '.metadata', contents: createMetadataFile() },
    { path: 'README.md', contents: createReadme(project, pages) },
    { path: 'lib/main.dart', contents: createMainFile(pages) },
    { path: 'lib/config/app_env.dart', contents: createAppEnvFile() },
    { path: 'lib/data/page_data_client.dart', contents: createPageDataClientFile() },
    { path: 'lib/models/generated_models.dart', contents: createGeneratedModelsFile() },
    {
      path: 'lib/generated/project_manifest.dart',
      contents: createProjectManifestFile(project, pages)
    },
    { path: 'lib/render/page_renderer.dart', contents: createPageRendererFile() }
  ];

  for (const page of pages) {
    files.push({
      path: `lib/pages/${page.fileName}`,
      contents: createPageFile(page)
    });
  }

  console.info(`${LOG_PREFIX} Prepared ${files.length} Flutter file(s)`);
  return files;
};

export const FlutterAdapter: CodegenAdapter = {
  name: 'flutter',
  target: 'flutter',
  async generate(ir) {
    console.info(`${LOG_PREFIX} Starting Flutter code generation for "${ir.metadata.name}"`);

    const project = normalizeProject(ir);
    const files = buildFlutterFiles(project);

    const bundle = createBundle('flutter', files, {
      irVersion: project.version,
      summary: `Flutter app for ${project.metadata.name}`,
      entryFile: 'lib/main.dart',
      metadata: {
        pages: project.pages.length,
        routeCount: project.pages.length
      }
    });

    console.info(`${LOG_PREFIX} Bundle created with ${bundle.files.length} file(s), id="${bundle.id}"`);
    return bundle;
  }
};
